meta_product_name: "Bootcampers"
meta_title: "Bootcampers - Code sans te soucier du reste"
meta_description: "Grâce à Bootcampers développe des projets en freelance sans t'encombrer des tâches administratives et de la négociation client."
meta_image: "background-bootcampers.jpeg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@bootcampers.co"              # indispensable pour les Twitter Cards
