# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d24504db19754f9abd76578b5ee2e7f67dfc17c68a0b0915711d74a3bc09ba7b1b0a5c98b1459bcb02bf3771815bb388852b2a1b7e76d5d40e826da1f789e11

test:
  secret_key_base: 329a624e35946424efc8fd203cf4317c7f38879e2fdbc6ad27638a61a6891f4c6ed65a7a16937317224d5f9194ded520421593def85354c5b2b1d9360e9258d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
